tft:
  - name: "Test 1"
    namespace: "default"
    # test cases can be specified individually i.e "1,2,3,6" or as a range i.e. "1-9,15-19"
    test_cases: "1"
    duration: "30"
    # Location of artifacts from run can be specified: default <working-dir>/ft-logs/
    # logs: "/tmp/ft-logs"
    connections:
      - name: "Connection_1"
        # supported types: iperf-tcp, iperf-udp, netperf-tcp-stream, netperf-tcp-rr
        type: "iperf-tcp"
        instances: 1
        server:
          - name: "worker-229"
            persistent: "false"
            sriov: "true"
        client:
          - name: "worker-230"
            sriov: "true"
        plugins:
          - name: measure_cpu
          - name: measure_power
          - name: validate_offload
        # (Optional) Secondary network is required for tests 27-29. For these tests, it is mandatory; if not specified, it will default to "tft-secondary." For other tests, 
        # the secondary network is optional. If it is undefined, the tests will default to using the primary network.
        # (Optional) Define the resource name for SRIOV pods, where the resource requests and limits are configured. Defaults to None if not set. If the user specified the secondary nad 
        # it will try to autopopulate the resource name based on the nad. 
        # resource_name: "openshift.io/dpu"
kubeconfig:
kubeconfig_infra:
