name: Build PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
    - name: Build Multiarch image
      run: |
        docker buildx build \
          --file ./Containerfile \
          --platform linux/arm64,linux/amd64 \
          .
